PF2Room0:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room1:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $86 ; |.XX....X| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room2:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $18 ; |...XX...| mirrored
    .byte $1C ; |..XXX...| mirrored
PF2Room3:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $1F ; |XXXXX...| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $1F ; |XXXXX...| mirrored
    .byte $1F ; |XXXXX...| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room4:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room5:
    .byte $0C ; |..XX....| mirrored
    .byte $0C ; |..XX....| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $55 ; |X.X.X.X.| mirrored
    .byte $7F ; |XXXXXXX.| mirrored
    .byte $7F ; |XXXXXXX.| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
PF2Room6:
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
PF2Room7:
    .byte $7F ; |XXXXXXX.| mirrored
    .byte $55 ; |X.X.X.X.| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $1C ; |..XXX...| mirrored
    .byte $1C ; |..XXX...| mirrored
    .byte $1E ; |.XXXX...| mirrored
    .byte $5E ; |.XXXX.X.| mirrored
    .byte $6E ; |.XXX.XX.| mirrored
    .byte $CE ; |.XXX..XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $F8 ; |...XXXXX| mirrored
PF2Room8:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $7C ; |..XXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
PF2Room9:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room10:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $1C ; |..XXX...| mirrored
    .byte $1C ; |..XXX...| mirrored
    .byte $1E ; |.XXXX...| mirrored
    .byte $5E ; |.XXXX.X.| mirrored
    .byte $6E ; |.XXX.XX.| mirrored
    .byte $CE ; |.XXX..XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $F8 ; |...XXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room11:
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
PF2Room12:
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $0C ; |..XX....| mirrored
    .byte $1E ; |.XXXX...| mirrored
    .byte $3F ; |XXXXXX..| mirrored
PF2Room13:
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $01 ; |X.......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $07 ; |XXX.....| mirrored
    .byte $07 ; |XXX.....| mirrored
    .byte $07 ; |XXX.....| mirrored
PF2Room14:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room15:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored

