PF1Room0:
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $E0 ; |XXX.....|
    .byte $E0 ; |XXX.....|
    .byte $F0 ; |XXXX....|
PF1Room1:
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $81 ; |X......X|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $81 ; |X......X|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
PF1Room2:
    .byte $3C ; |..XXXX..|
    .byte $3C ; |..XXXX..|
    .byte $38 ; |..XXX...|
    .byte $18 ; |...XX...|
    .byte $10 ; |...X....|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room3:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $01 ; |.......X|
    .byte $03 ; |......XX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
    .byte $01 ; |.......X|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room4:
    .byte $40 ; |.X......|
    .byte $40 ; |.X......|
    .byte $40 ; |.X......|
    .byte $40 ; |.X......|
    .byte $40 ; |.X......|
    .byte $C0 ; |XX......|
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $F0 ; |XXXX....|
    .byte $F0 ; |XXXX....|
    .byte $40 ; |.X......|
    .byte $40 ; |.X......|
    .byte $40 ; |.X......|
    .byte $40 ; |.X......|
PF1Room5:
    .byte $80 ; |X.......|
    .byte $00 ; |........|
    .byte $80 ; |X.......|
    .byte $00 ; |........|
    .byte $86 ; |X....XX.|
    .byte $06 ; |.....XX.|
    .byte $80 ; |X.......|
    .byte $00 ; |........|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $40 ; |.X......|
    .byte $EA ; |XXX.X.X.|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
PF1Room6:
    .byte $00 ; |........|
    .byte $B6 ; |X.XX.XX.|
    .byte $B6 ; |X.XX.XX.|
    .byte $00 ; |........|
    .byte $B6 ; |X.XX.XX.|
    .byte $B6 ; |X.XX.XX.|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $B6 ; |X.XX.XX.|
    .byte $B6 ; |X.XX.XX.|
    .byte $00 ; |........|
    .byte $B6 ; |X.XX.XX.|
    .byte $B6 ; |X.XX.XX.|
    .byte $00 ; |........|
PF1Room7:
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $82 ; |X.....X.|
PF1Room8:
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
PF1Room9:
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C3 ; |XX....XX|
    .byte $C7 ; |XX...XXX|
    .byte $C7 ; |XX...XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $C7 ; |XX...XXX|
    .byte $C7 ; |XX...XXX|
    .byte $C3 ; |XX....XX|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
PF1Room10:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $14 ; |...X.X..|
    .byte $14 ; |...X.X..|
    .byte $1C ; |...XXX..|
    .byte $14 ; |...X.X..|
    .byte $1C ; |...XXX..|
    .byte $00 ; |........|
PF1Room11:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $18 ; |...XX...|
    .byte $14 ; |...X.X..|
    .byte $18 ; |...XX...|
    .byte $14 ; |...X.X..|
    .byte $18 ; |...XX...|
    .byte $00 ; |........|
PF1Room12:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $1C ; |...XXX..|
    .byte $10 ; |...X....|
    .byte $10 ; |...X....|
    .byte $10 ; |...X....|
    .byte $1C ; |...XXX..|
    .byte $00 ; |........|
PF1Room13:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $18 ; |...XX...|
    .byte $14 ; |...X.X..|
    .byte $14 ; |...X.X..|
    .byte $14 ; |...X.X..|
    .byte $18 ; |...XX...|
    .byte $00 ; |........|
PF1Room14:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $1C ; |...XXX..|
    .byte $10 ; |...X....|
    .byte $18 ; |...XX...|
    .byte $10 ; |...X....|
    .byte $1C ; |...XXX..|
    .byte $00 ; |........|
PF1Room15:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $10 ; |...X....|
    .byte $10 ; |...X....|
    .byte $18 ; |...XX...|
    .byte $10 ; |...X....|
    .byte $1C ; |...XXX..|
    .byte $00 ; |........|

