PF1Room16:
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
PF1Room17:
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C3 ; |XX....XX|
    .byte $C7 ; |XX...XXX|
    .byte $C7 ; |XX...XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $C7 ; |XX...XXX|
    .byte $C7 ; |XX...XXX|
    .byte $C3 ; |XX....XX|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
PF1Room18:
    .byte $20 ; |..X.....|
    .byte $20 ; |..X.....|
    .byte $20 ; |..X.....|
    .byte $20 ; |..X.....|
    .byte $20 ; |..X.....|
    .byte $3F ; |..XXXXXX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $3F ; |..XXXXXX|
    .byte $20 ; |..X.....|
    .byte $20 ; |..X.....|
    .byte $20 ; |..X.....|
    .byte $20 ; |..X.....|
    .byte $20 ; |..X.....|
PF1Room19:
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $81 ; |X......X|
    .byte $81 ; |X......X|
    .byte $01 ; |.......X|
    .byte $01 ; |.......X|
    .byte $01 ; |.......X|
    .byte $01 ; |.......X|
    .byte $81 ; |X......X|
    .byte $81 ; |X......X|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
PF1Room20:
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
PF1Room21:
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $8C ; |X...XX..|
    .byte $8C ; |X...XX..|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $8C ; |X...XX..|
    .byte $8C ; |X...XX..|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
PF1Room22:
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $8C ; |X...XX..|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $8C ; |X...XX..|
    .byte $0C ; |....XX..|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $0C ; |....XX..|
    .byte $8C ; |X...XX..|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $8C ; |X...XX..|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
PF1Room23:
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
PF1Room24:
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $83 ; |X.....XX|
    .byte $03 ; |......XX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
PF1Room25:
    .byte $E0 ; |XXX.....|
    .byte $E0 ; |XXX.....|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $07 ; |.....XXX|
    .byte $06 ; |.....XX.|
    .byte $06 ; |.....XX.|
    .byte $07 ; |.....XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E0 ; |XXX.....|
    .byte $E0 ; |XXX.....|
PF1Room26:
    .byte $80 ; |X.......|
    .byte $86 ; |X....XX.|
    .byte $86 ; |X....XX.|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $B8 ; |X.XXX...|
    .byte $B8 ; |X.XXX...|
    .byte $BF ; |X.XXXXXX|
    .byte $BF ; |X.XXXXXX|
    .byte $BF ; |X.XXXXXX|
    .byte $BF ; |X.XXXXXX|
PF1Room27:
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
PF1Room28:
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $81 ; |X......X|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $81 ; |X......X|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
PF1Room29:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $FF ; |XXXXXXXX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $FF ; |XXXXXXXX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room30:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $C0 ; |XX......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $C0 ; |XX......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room31:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $10 ; |...X....|
    .byte $10 ; |...X....|
    .byte $18 ; |...XX...|
    .byte $10 ; |...X....|
    .byte $1C ; |...XXX..|
    .byte $00 ; |........|

