PF2Room12:
    .byte $3F ; |XXXXXX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $18 ; |...XX...| mirrored
    .byte $18 ; |...XX...| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $3F ; |XXXXXX..| mirrored
PF2Room13:
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $7C ; |..XXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7F ; |XXXXXXX.| mirrored
    .byte $7F ; |XXXXXXX.| mirrored
PF2Room14:
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
PF2Room15:
    .byte $3F ; |XXXXXX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $01 ; |X.......| mirrored
    .byte $01 ; |X.......| mirrored
    .byte $01 ; |X.......| mirrored
    .byte $01 ; |X.......| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $3F ; |XXXXXX..| mirrored
PF2Room16:
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
PF2Room17:
    .byte $3F ; |XXXXXX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $3F ; |XXXXXX..| mirrored
PF2Room18:
    .byte $3F ; |XXXXXX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $0C ; |..XX....| mirrored
    .byte $0C ; |..XX....| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $0C ; |..XX....| mirrored
    .byte $0C ; |..XX....| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $0C ; |..XX....| mirrored
    .byte $0C ; |..XX....| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $0C ; |..XX....| mirrored
    .byte $0C ; |..XX....| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $3F ; |XXXXXX..| mirrored
PF2Room19:
    .byte $3F ; |XXXXXX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $3C ; |..XXXX..| mirrored
    .byte $18 ; |...XX...| mirrored
    .byte $10 ; |....X...| mirrored
    .byte $E0 ; |.....XXX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $3F ; |XXXXXX..| mirrored
PF2Room20:
    .byte $3F ; |XXXXXX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $3F ; |XXXXXX..| mirrored
PF2Room21:
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3E ; |.XXXXX..| mirrored
    .byte $3E ; |.XXXXX..| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $3E ; |.XXXXX..| mirrored
    .byte $3E ; |.XXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
PF2Room22:
    .byte $3F ; |XXXXXX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $01 ; |X.......| mirrored
    .byte $01 ; |X.......| mirrored
    .byte $07 ; |XXX.....| mirrored
    .byte $07 ; |XXX.....| mirrored
    .byte $00 ; |........| mirrored
    .byte $3F ; |XXXXXX..| mirrored
PF2Room23:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored

