PF1Room12:
    .byte $FF ; |XXXXXXXX|
    .byte $E0 ; |XXX.....|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $E0 ; |XXX.....|
    .byte $FF ; |XXXXXXXX|
PF1Room13:
    .byte $FF ; |XXXXXXXX|
    .byte $C0 ; |XX......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $C0 ; |XX......|
    .byte $FF ; |XXXXXXXX|
PF1Room14:
    .byte $FF ; |XXXXXXXX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $7C ; |.XXXXX..|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
PF1Room15:
    .byte $FF ; |XXXXXXXX|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $81 ; |X......X|
    .byte $81 ; |X......X|
    .byte $01 ; |.......X|
    .byte $01 ; |.......X|
    .byte $01 ; |.......X|
    .byte $01 ; |.......X|
    .byte $81 ; |X......X|
    .byte $81 ; |X......X|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $FF ; |XXXXXXXX|
PF1Room16:
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $FF ; |XXXXXXXX|
PF1Room17:
    .byte $FF ; |XXXXXXXX|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $8C ; |X...XX..|
    .byte $8C ; |X...XX..|
    .byte $8C ; |X...XX..|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $8C ; |X...XX..|
    .byte $8C ; |X...XX..|
    .byte $8C ; |X...XX..|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $FF ; |XXXXXXXX|
PF1Room18:
    .byte $FF ; |XXXXXXXX|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $8C ; |X...XX..|
    .byte $8C ; |X...XX..|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $8C ; |X...XX..|
    .byte $0C ; |....XX..|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $0C ; |....XX..|
    .byte $8C ; |X...XX..|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $8C ; |X...XX..|
    .byte $8C ; |X...XX..|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $FF ; |XXXXXXXX|
PF1Room19:
    .byte $FF ; |XXXXXXXX|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $FF ; |XXXXXXXX|
PF1Room20:
    .byte $FF ; |XXXXXXXX|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $83 ; |X.....XX|
    .byte $03 ; |......XX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $FF ; |XXXXXXXX|
PF1Room21:
    .byte $FF ; |XXXXXXXX|
    .byte $E0 ; |XXX.....|
    .byte $E0 ; |XXX.....|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $07 ; |.....XXX|
    .byte $06 ; |.....XX.|
    .byte $06 ; |.....XX.|
    .byte $07 ; |.....XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E0 ; |XXX.....|
    .byte $E0 ; |XXX.....|
    .byte $FF ; |XXXXXXXX|
PF1Room22:
    .byte $FF ; |XXXXXXXX|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $86 ; |X....XX.|
    .byte $86 ; |X....XX.|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $B8 ; |X.XXX...|
    .byte $B8 ; |X.XXX...|
    .byte $BF ; |X.XXXXXX|
    .byte $BF ; |X.XXXXXX|
    .byte $BF ; |X.XXXXXX|
    .byte $BF ; |X.XXXXXX|
    .byte $80 ; |X.......|
    .byte $FF ; |XXXXXXXX|
PF1Room23:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $30 ; |..XX....|
    .byte $28 ; |..X.X...|
    .byte $30 ; |..XX....|
    .byte $28 ; |..X.X...|
    .byte $30 ; |..XX....|

