PF2Room0:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $18 ; |...XX...| mirrored
    .byte $18 ; |...XX...| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room1:
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room2:
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
    .byte $20 ; |.....X..| mirrored
PF2Room3:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $3C ; |..XXXX..| mirrored
    .byte $18 ; |...XX...| mirrored
    .byte $10 ; |....X...| mirrored
    .byte $E0 ; |.....XXX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room4:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $1C ; |..XXX...| mirrored
    .byte $1C ; |..XXX...| mirrored
    .byte $1E ; |.XXXX...| mirrored
    .byte $5E ; |.XXXX.X.| mirrored
    .byte $6E ; |.XXX.XX.| mirrored
    .byte $CE ; |.XXX..XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $F8 ; |...XXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room5:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $86 ; |.XX....X| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room6:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $38 ; |...XXX..| mirrored
    .byte $28 ; |...X.X..| mirrored
    .byte $38 ; |...XXX..| mirrored
    .byte $28 ; |...X.X..| mirrored
    .byte $F8 ; |...XXXXX| mirrored
    .byte $F0 ; |....XXXX| mirrored
    .byte $E0 ; |.....XXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room7:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $70 ; |....XXX.| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $F0 ; |....XXXX| mirrored
    .byte $B8 ; |...XXX.X| mirrored
    .byte $EE ; |.XXX.XXX| mirrored
    .byte $B4 ; |..X.XX.X| mirrored
    .byte $52 ; |.X..X.X.| mirrored
    .byte $A8 ; |...X.X.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room8:
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $01 ; |X.......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $07 ; |XXX.....| mirrored
    .byte $07 ; |XXX.....| mirrored
    .byte $07 ; |XXX.....| mirrored
PF2Room9:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $7C ; |..XXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
PF2Room10:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room11:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $D2 ; |.X..X.XX| mirrored
    .byte $BF ; |XXXXXX.X| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $BA ; |.X.XXX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room12:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room13:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room14:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room15:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room16:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room17:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room18:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room19:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room20:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room21:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room22:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room23:
    .byte $7F ; |XXXXXXX.| mirrored
    .byte $55 ; |X.X.X.X.| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $1C ; |..XXX...| mirrored
    .byte $1C ; |..XXX...| mirrored
    .byte $1E ; |.XXXX...| mirrored
    .byte $5E ; |.XXXX.X.| mirrored
    .byte $6E ; |.XXX.XX.| mirrored
    .byte $CE ; |.XXX..XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $F8 ; |...XXXXX| mirrored
PF2Room24:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $01 ; |X.......| mirrored
    .byte $01 ; |X.......| mirrored
    .byte $07 ; |XXX.....| mirrored
    .byte $07 ; |XXX.....| mirrored
PF2Room25:
    .byte $02 ; |.X......| mirrored
    .byte $02 ; |.X......| mirrored
    .byte $02 ; |.X......| mirrored
    .byte $02 ; |.X......| mirrored
    .byte $02 ; |.X......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $02 ; |.X......| mirrored
    .byte $02 ; |.X......| mirrored
    .byte $02 ; |.X......| mirrored
    .byte $02 ; |.X......| mirrored
    .byte $02 ; |.X......| mirrored
PF2Room26:
    .byte $0C ; |..XX....| mirrored
    .byte $0C ; |..XX....| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $55 ; |X.X.X.X.| mirrored
    .byte $7F ; |XXXXXXX.| mirrored
    .byte $7F ; |XXXXXXX.| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
PF2Room27:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room28:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $1F ; |XXXXX...| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $1F ; |XXXXX...| mirrored
    .byte $1F ; |XXXXX...| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room29:
    .byte $3E ; |.XXXXX..| mirrored
    .byte $FE ; |.XXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FE ; |.XXXXXXX| mirrored
    .byte $3E ; |.XXXXX..| mirrored
PF2Room30:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room31:
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored

