SprGanon0:
    .byte $03 ; |......XX|
    .byte $02 ; |......X.|
    .byte $01 ; |.......X|
    .byte $01 ; |.......X|
    .byte $03 ; |......XX|
    .byte $00 ; |........|
    .byte $0C ; |....XX..|
    .byte $18 ; |...XX...|
    .byte $39 ; |..XXX..X|
    .byte $3F ; |..XXXXXX|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $3E ; |..XXXXX.|
    .byte $3D ; |..XXXX.X|
    .byte $3F ; |..XXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $3F ; |..XXXXXX|
    .byte $1F ; |...XXXXX|
    .byte $0F ; |....XXXX|
    .byte $00 ; |........|
    .byte $03 ; |......XX|
SprGanon1:
    .byte $F0 ; |XXXX....|
    .byte $F3 ; |XXXX..XX|
    .byte $F7 ; |XXXX.XXX|
    .byte $87 ; |X....XXX|
    .byte $3F ; |..XXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $3F ; |..XXXXXX|
    .byte $3F ; |..XXXXXX|
    .byte $00 ; |........|
    .byte $7F ; |.XXXXXXX|
    .byte $78 ; |.XXXX...|
    .byte $71 ; |.XXX...X|
    .byte $74 ; |.XXX.X..|
    .byte $36 ; |..XX.XX.|
    .byte $B8 ; |X.XXX...|
    .byte $BF ; |X.XXXXXX|
    .byte $A3 ; |X.X...XX|
    .byte $84 ; |X....X..|
    .byte $88 ; |X...X...|
    .byte $6F ; |.XX.XXXX|
    .byte $FC ; |XXXXXX..|
    .byte $FA ; |XXXXX.X.|
    .byte $7A ; |.XXXX.X.|
    .byte $7C ; |.XXXXX..|
    .byte $BF ; |X.XXXXXX|
    .byte $D9 ; |XX.XX..X|
    .byte $BB ; |X.XXX.XX|
    .byte $77 ; |.XXX.XXX|
    .byte $F7 ; |XXXX.XXX|
    .byte $F3 ; |XXXX..XX|
SprGanon2:
    .byte $0F ; |....XXXX|
    .byte $CF ; |XX..XXXX|
    .byte $EF ; |XXX.XXXX|
    .byte $E1 ; |XXX....X|
    .byte $FC ; |XXXXXX..|
    .byte $FE ; |XXXXXXX.|
    .byte $FF ; |XXXXXXXX|
    .byte $FE ; |XXXXXXX.|
    .byte $FC ; |XXXXXX..|
    .byte $FC ; |XXXXXX..|
    .byte $00 ; |........|
    .byte $FE ; |XXXXXXX.|
    .byte $1E ; |...XXXX.|
    .byte $8E ; |X...XXX.|
    .byte $2E ; |..X.XXX.|
    .byte $6C ; |.XX.XX..|
    .byte $1D ; |...XXX.X|
    .byte $FD ; |XXXXXX.X|
    .byte $C5 ; |XX...X.X|
    .byte $21 ; |..X....X|
    .byte $11 ; |...X...X|
    .byte $F6 ; |XXXX.XX.|
    .byte $3F ; |..XXXXXX|
    .byte $5F ; |.X.XXXXX|
    .byte $5E ; |.X.XXXX.|
    .byte $3E ; |..XXXXX.|
    .byte $FD ; |XXXXXX.X|
    .byte $9B ; |X..XX.XX|
    .byte $DD ; |XX.XXX.X|
    .byte $EE ; |XXX.XXX.|
    .byte $EF ; |XXX.XXXX|
    .byte $CF ; |XX..XXXX|
SprGanon3:
    .byte $C0 ; |XX......|
    .byte $40 ; |.X......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $C0 ; |XX......|
    .byte $00 ; |........|
    .byte $30 ; |..XX....|
    .byte $18 ; |...XX...|
    .byte $9C ; |X..XXX..|
    .byte $FC ; |XXXXXX..|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $7C ; |.XXXXX..|
    .byte $BC ; |X.XXXX..|
    .byte $FC ; |XXXXXX..|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FC ; |XXXXXX..|
    .byte $F8 ; |XXXXX...|
    .byte $F0 ; |XXXX....|
    .byte $00 ; |........|
    .byte $C0 ; |XX......|
SprGanon4:
    .byte $E6 ; |XXX..XX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $4C ; |.X..XX..|
    .byte $3C ; |..XXXX..|
    .byte $3C ; |..XXXX..|
    .byte $38 ; |..XXX...|
    .byte $3C ; |..XXXX..|
    .byte $7E ; |.XXXXXX.|
    .byte $7E ; |.XXXXXX.|
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $7E ; |.XXXXXX.|
    .byte $3E ; |..XXXXX.|
    .byte $3D ; |..XXXX.X|
    .byte $43 ; |.X....XX|
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $3F ; |..XXXXXX|
    .byte $3F ; |..XXXXXX|
    .byte $1F ; |...XXXXX|
    .byte $0F ; |....XXXX|
    .byte $03 ; |......XX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $01 ; |.......X|
    .byte $00 ; |........|
SprGanon5:
    .byte $78 ; |.XXXX...|
    .byte $7D ; |.XXXXX.X|
    .byte $FE ; |XXXXXXX.|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FE ; |XXXXXXX.|
    .byte $FB ; |XXXXX.XX|
    .byte $7F ; |.XXXXXXX|
    .byte $1E ; |...XXXX.|
    .byte $79 ; |.XXXX..X|
    .byte $74 ; |.XXX.X..|
    .byte $76 ; |.XXX.XX.|
    .byte $78 ; |.XXXX...|
    .byte $7F ; |.XXXXXXX|
    .byte $70 ; |.XXX....|
    .byte $6F ; |.XX.XXXX|
    .byte $A8 ; |X.X.X...|
    .byte $D8 ; |XX.XX...|
    .byte $DD ; |XX.XXX.X|
    .byte $EA ; |XXX.X.X.|
    .byte $EA ; |XXX.X.X.|
    .byte $F0 ; |XXXX....|
    .byte $DF ; |XX.XXXXX|
    .byte $D8 ; |XX.XX...|
    .byte $33 ; |..XX..XX|
    .byte $37 ; |..XX.XXX|
    .byte $FF ; |XXXXXXXX|
    .byte $F7 ; |XXXX.XXX|
    .byte $F0 ; |XXXX....|
    .byte $00 ; |........|
SprGanon6:
    .byte $00 ; |........|
    .byte $80 ; |X.......|
    .byte $C0 ; |XX......|
    .byte $40 ; |.X......|
    .byte $C0 ; |XX......|
    .byte $C1 ; |XX.....X|
    .byte $FF ; |XXXXXXXX|
    .byte $AB ; |X.X.X.XX|
    .byte $FD ; |XXXXXX.X|
    .byte $FE ; |XXXXXXX.|
    .byte $3F ; |..XXXXXX|
    .byte $9F ; |X..XXXXX|
    .byte $2F ; |..X.XXXX|
    .byte $6F ; |.XX.XXXX|
    .byte $1F ; |...XXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $9F ; |X..XXXXX|
    .byte $6F ; |.XX.XXXX|
    .byte $F7 ; |XXXX.XXX|
    .byte $C6 ; |XX...XX.|
    .byte $B9 ; |X.XXX..X|
    .byte $BF ; |X.XXXXXX|
    .byte $BF ; |X.XXXXXX|
    .byte $BF ; |X.XXXXXX|
    .byte $DE ; |XX.XXXX.|
    .byte $20 ; |..X.....|
    .byte $BD ; |X.XXXX.X|
    .byte $FE ; |XXXXXXX.|
    .byte $EE ; |XXX.XXX.|
    .byte $06 ; |.....XX.|
    .byte $03 ; |......XX|
SprGanon7:
    .byte $7F ; |.XXXXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $3A ; |..XXX.X.|
    .byte $DC ; |XX.XXX..|
    .byte $E4 ; |XXX..X..|
    .byte $F8 ; |XXXXX...|
    .byte $FC ; |XXXXXX..|
    .byte $F8 ; |XXXXX...|
    .byte $F8 ; |XXXXX...|
    .byte $F8 ; |XXXXX...|
    .byte $78 ; |.XXXX...|
    .byte $B0 ; |X.XX....|
    .byte $E0 ; |XXX.....|
    .byte $C0 ; |XX......|
    .byte $E0 ; |XXX.....|
    .byte $E0 ; |XXX.....|
    .byte $E0 ; |XXX.....|
    .byte $D8 ; |XX.XX...|
    .byte $BC ; |X.XXXX..|
    .byte $7E ; |.XXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FC ; |XXXXXX..|
    .byte $FA ; |XXXXX.X.|
    .byte $E6 ; |XXX..XX.|
    .byte $1E ; |...XXXX.|
    .byte $FC ; |XXXXXX..|
    .byte $F0 ; |XXXX....|
    .byte $C0 ; |XX......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|

