SprManhandla16_0:
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
    .byte $71 ; |.XXX...X|
    .byte $71 ; |.XXX...X|
    .byte $FB ; |XXXXX.XX|
    .byte $FB ; |XXXXX.XX|
    .byte $0F ; |....XXXX|
    .byte $0F ; |....XXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FB ; |XXXXX.XX|
    .byte $FB ; |XXXXX.XX|
    .byte $71 ; |.XXX...X|
    .byte $71 ; |.XXX...X|
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
SprManhandla16_1:
    .byte $40 ; |.X......|
    .byte $40 ; |.X......|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $8E ; |X...XXX.|
    .byte $8E ; |X...XXX.|
    .byte $DF ; |XX.XXXXX|
    .byte $DF ; |XX.XXXXX|
    .byte $F0 ; |XXXX....|
    .byte $F0 ; |XXXX....|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $DF ; |XX.XXXXX|
    .byte $DF ; |XX.XXXXX|
    .byte $8E ; |X...XXX.|
    .byte $8E ; |X...XXX.|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $40 ; |.X......|
    .byte $40 ; |.X......|
SprManhandla16_2:
    .byte $34 ; |..XX.X..|
    .byte $34 ; |..XX.X..|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $3C ; |..XXXX..|
    .byte $3C ; |..XXXX..|
    .byte $18 ; |...XX...|
    .byte $18 ; |...XX...|
    .byte $BD ; |X.XXXX.X|
    .byte $BD ; |X.XXXX.X|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $BD ; |X.XXXX.X|
    .byte $BD ; |X.XXXX.X|
    .byte $18 ; |...XX...|
    .byte $18 ; |...XX...|
    .byte $3C ; |..XXXX..|
    .byte $3C ; |..XXXX..|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $34 ; |..XX.X..|
    .byte $34 ; |..XX.X..|
SprManhandla12_0:
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
    .byte $71 ; |.XXX...X|
    .byte $71 ; |.XXX...X|
    .byte $FB ; |XXXXX.XX|
    .byte $FB ; |XXXXX.XX|
    .byte $0F ; |....XXXX|
    .byte $0F ; |....XXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FB ; |XXXXX.XX|
    .byte $FB ; |XXXXX.XX|
    .byte $71 ; |.XXX...X|
    .byte $71 ; |.XXX...X|
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
SprManhandla12_1:
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $8E ; |X...XXX.|
    .byte $8E ; |X...XXX.|
    .byte $DF ; |XX.XXXXX|
    .byte $DF ; |XX.XXXXX|
    .byte $F0 ; |XXXX....|
    .byte $F0 ; |XXXX....|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $DF ; |XX.XXXXX|
    .byte $DF ; |XX.XXXXX|
    .byte $8E ; |X...XXX.|
    .byte $8E ; |X...XXX.|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $40 ; |.X......|
    .byte $40 ; |.X......|
SprManhandla12_2:
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
    .byte $71 ; |.XXX...X|
    .byte $71 ; |.XXX...X|
    .byte $FB ; |XXXXX.XX|
    .byte $FB ; |XXXXX.XX|
    .byte $0F ; |....XXXX|
    .byte $0F ; |....XXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FB ; |XXXXX.XX|
    .byte $FB ; |XXXXX.XX|
    .byte $71 ; |.XXX...X|
    .byte $71 ; |.XXX...X|
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
SprManhandla12_3:
    .byte $40 ; |.X......|
    .byte $40 ; |.X......|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $60 ; |.XX.....|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $8E ; |X...XXX.|
    .byte $8E ; |X...XXX.|
    .byte $DF ; |XX.XXXXX|
    .byte $DF ; |XX.XXXXX|
    .byte $F0 ; |XXXX....|
    .byte $F0 ; |XXXX....|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $DF ; |XX.XXXXX|
    .byte $DF ; |XX.XXXXX|
    .byte $8E ; |X...XXX.|
    .byte $8E ; |X...XXX.|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
SprManhandla12_4:
    .byte $3C ; |..XXXX..|
    .byte $3C ; |..XXXX..|
    .byte $18 ; |...XX...|
    .byte $18 ; |...XX...|
    .byte $BD ; |X.XXXX.X|
    .byte $BD ; |X.XXXX.X|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $BD ; |X.XXXX.X|
    .byte $BD ; |X.XXXX.X|
    .byte $18 ; |...XX...|
    .byte $18 ; |...XX...|
    .byte $3C ; |..XXXX..|
    .byte $3C ; |..XXXX..|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $34 ; |..XX.X..|
    .byte $34 ; |..XX.X..|
SprManhandla12_5:
    .byte $34 ; |..XX.X..|
    .byte $34 ; |..XX.X..|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $3C ; |..XXXX..|
    .byte $3C ; |..XXXX..|
    .byte $18 ; |...XX...|
    .byte $18 ; |...XX...|
    .byte $BD ; |X.XXXX.X|
    .byte $BD ; |X.XXXX.X|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $BD ; |X.XXXX.X|
    .byte $BD ; |X.XXXX.X|
    .byte $18 ; |...XX...|
    .byte $18 ; |...XX...|
    .byte $3C ; |..XXXX..|
    .byte $3C ; |..XXXX..|
SprManhandla8_0:
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
    .byte $71 ; |.XXX...X|
    .byte $71 ; |.XXX...X|
    .byte $FB ; |XXXXX.XX|
    .byte $FB ; |XXXXX.XX|
    .byte $0F ; |....XXXX|
    .byte $0F ; |....XXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FB ; |XXXXX.XX|
    .byte $FB ; |XXXXX.XX|
    .byte $71 ; |.XXX...X|
    .byte $71 ; |.XXX...X|
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
SprManhandla8_1:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $70 ; |.XXX....|
    .byte $70 ; |.XXX....|
    .byte $F0 ; |XXXX....|
    .byte $F0 ; |XXXX....|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $F0 ; |XXXX....|
    .byte $F0 ; |XXXX....|
    .byte $F0 ; |XXXX....|
    .byte $F0 ; |XXXX....|
    .byte $70 ; |.XXX....|
    .byte $70 ; |.XXX....|
    .byte $00 ; |........|
    .byte $00 ; |........|

