SprAqua0:
    .byte $78 ; |.XXXX...|
    .byte $38 ; |..XXX...|
    .byte $0C ; |....XX..|
    .byte $3C ; |..XXXX..|
    .byte $0F ; |....XXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $1F ; |...XXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $3F ; |..XXXXXX|
    .byte $0F ; |....XXXX|
    .byte $07 ; |.....XXX|
    .byte $66 ; |.XX..XX.|
    .byte $16 ; |...X.XX.|
    .byte $FE ; |XXXXXXX.|
    .byte $6C ; |.XX.XX..|
    .byte $32 ; |..XX..X.|
    .byte $5A ; |.X.XX.X.|
    .byte $81 ; |X......X|
SprAqua1:
    .byte $78 ; |.XXXX...|
    .byte $38 ; |..XXX...|
    .byte $0C ; |....XX..|
    .byte $3C ; |..XXXX..|
    .byte $0F ; |....XXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $1F ; |...XXXXX|
    .byte $7F ; |.XXXXXXX|
    .byte $3F ; |..XXXXXX|
    .byte $0F ; |....XXXX|
    .byte $67 ; |.XX..XXX|
    .byte $36 ; |..XX.XX.|
    .byte $16 ; |...X.XX.|
    .byte $FE ; |XXXXXXX.|
    .byte $6C ; |.XX.XX..|
    .byte $32 ; |..XX..X.|
    .byte $5A ; |.X.XX.X.|
    .byte $81 ; |X......X|
SprAqua2:
    .byte $3C ; |..XXXX..|
    .byte $3C ; |..XXXX..|
    .byte $1C ; |...XXX..|
    .byte $1E ; |...XXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FF ; |XXXXXXXX|
    .byte $81 ; |X......X|
    .byte $7E ; |.XXXXXX.|
    .byte $79 ; |.XXXX..X|
    .byte $B7 ; |X.XX.XXX|
    .byte $01 ; |.......X|
    .byte $02 ; |......X.|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|

