SprTitleDemo0:
    .byte $0F ; |....XXXX|
    .byte $0E ; |....XXX.|
    .byte $07 ; |.....XXX|
    .byte $03 ; |......XX|
    .byte $01 ; |.......X|
    .byte $00 ; |........|
    .byte $0C ; |....XX..|
    .byte $0F ; |....XXXX|
    .byte $00 ; |........|
    .byte $12 ; |...X..X.|
    .byte $12 ; |...X..X.|
    .byte $13 ; |...X..XX|
    .byte $12 ; |...X..X.|
    .byte $3A ; |..XXX.X.|
SprTitleDemo1:
    .byte $FB ; |XXXXX.XX|
    .byte $1B ; |...XX.XX|
    .byte $03 ; |......XX|
    .byte $83 ; |X.....XX|
    .byte $C3 ; |XX....XX|
    .byte $E3 ; |XXX...XX|
    .byte $73 ; |.XXX..XX|
    .byte $FB ; |XXXXX.XX|
    .byte $00 ; |........|
    .byte $B9 ; |X.XXX..X|
    .byte $A1 ; |X.X....X|
    .byte $B1 ; |X.XX...X|
    .byte $A1 ; |X.X....X|
    .byte $B9 ; |X.XXX..X|
SprTitleDemo2:
    .byte $FB ; |XXXXX.XX|
    .byte $1B ; |...XX.XX|
    .byte $03 ; |......XX|
    .byte $C3 ; |XX....XX|
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
    .byte $1B ; |...XX.XX|
    .byte $FB ; |XXXXX.XX|
    .byte $00 ; |........|
    .byte $DD ; |XX.XXX.X|
    .byte $11 ; |...X...X|
    .byte $19 ; |...XX..X|
    .byte $11 ; |...X...X|
    .byte $1D ; |...XXX.X|
SprTitleDemo3:
    .byte $F7 ; |XXXX.XXX|
    .byte $36 ; |..XX.XX.|
    .byte $06 ; |.....XX.|
    .byte $06 ; |.....XX.|
    .byte $06 ; |.....XX.|
    .byte $06 ; |.....XX.|
    .byte $06 ; |.....XX.|
    .byte $07 ; |.....XXX|
    .byte $00 ; |........|
    .byte $DD ; |XX.XXX.X|
    .byte $51 ; |.X.X...X|
    .byte $19 ; |...XX..X|
    .byte $11 ; |...X...X|
    .byte $DD ; |XX.XXX.X|
SprTitleDemo4:
    .byte $E6 ; |XXX..XX.|
    .byte $76 ; |.XXX.XX.|
    .byte $36 ; |..XX.XX.|
    .byte $37 ; |..XX.XXX|
    .byte $36 ; |..XX.XX.|
    .byte $37 ; |..XX.XXX|
    .byte $73 ; |.XXX..XX|
    .byte $E1 ; |XXX....X|
    .byte $00 ; |........|
    .byte $58 ; |.X.XX...|
    .byte $54 ; |.X.X.X..|
    .byte $54 ; |.X.X.X..|
    .byte $54 ; |.X.X.X..|
    .byte $98 ; |X..XX...|
SprTitleDemo5:
    .byte $70 ; |.XXX....|
    .byte $70 ; |.XXX....|
    .byte $30 ; |..XX....|
    .byte $F0 ; |XXXX....|
    .byte $30 ; |..XX....|
    .byte $30 ; |..XX....|
    .byte $B0 ; |X.XX....|
    .byte $F0 ; |XXXX....|
    .byte $00 ; |........|
    .byte $E8 ; |XXX.X...|
    .byte $A8 ; |X.X.X...|
    .byte $AC ; |X.X.XX..|
    .byte $A8 ; |X.X.X...|
    .byte $EE ; |XXX.XXX.|

