PF2Room0:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $F8 ; |...XXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $F8 ; |...XXXXX| mirrored
    .byte $F8 ; |...XXXXX| mirrored
    .byte $F0 ; |....XXXX| mirrored
    .byte $E0 ; |.....XXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room1:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $B0 ; |....XX.X| mirrored
    .byte $B0 ; |....XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $B0 ; |....XX.X| mirrored
    .byte $B0 ; |....XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room2:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room3:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $3C ; |..XXXX..| mirrored
    .byte $18 ; |...XX...| mirrored
    .byte $10 ; |....X...| mirrored
    .byte $E0 ; |.....XXX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room4:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $3C ; |..XXXX..| mirrored
    .byte $3C ; |..XXXX..| mirrored
    .byte $1E ; |.XXXX...| mirrored
    .byte $5E ; |.XXXX.X.| mirrored
    .byte $6E ; |.XXX.XX.| mirrored
    .byte $CE ; |.XXX..XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $F8 ; |...XXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room5:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $04 ; |..X.....| mirrored
    .byte $04 ; |..X.....| mirrored
    .byte $0E ; |.XXX....| mirrored
    .byte $04 ; |..X.....| mirrored
    .byte $00 ; |........| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $C4 ; |..X...XX| mirrored
    .byte $84 ; |..X....X| mirrored
    .byte $0E ; |.XXX....| mirrored
    .byte $04 ; |..X.....| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room6:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $78 ; |...XXXX.| mirrored
    .byte $68 ; |...X.XX.| mirrored
    .byte $78 ; |...XXXX.| mirrored
    .byte $E8 ; |...X.XXX| mirrored
    .byte $B8 ; |...XXX.X| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $E0 ; |.....XXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room7:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $70 ; |....XXX.| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $F0 ; |....XXXX| mirrored
    .byte $B8 ; |...XXX.X| mirrored
    .byte $EE ; |.XXX.XXX| mirrored
    .byte $B4 ; |..X.XX.X| mirrored
    .byte $52 ; |.X..X.X.| mirrored
    .byte $A8 ; |...X.X.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room8:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $60 ; |.....XX.| mirrored
    .byte $E0 ; |.....XXX| mirrored
    .byte $90 ; |....X..X| mirrored
    .byte $D0 ; |....X.XX| mirrored
    .byte $70 ; |....XXX.| mirrored
    .byte $E0 ; |.....XXX| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room9:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $78 ; |...XXXX.| mirrored
    .byte $7C ; |..XXXXX.| mirrored
    .byte $7C ; |..XXXXX.| mirrored
    .byte $7C ; |..XXXXX.| mirrored
    .byte $7C ; |..XXXXX.| mirrored
    .byte $3C ; |..XXXX..| mirrored
PF2Room10:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room11:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
PF2Room12:
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $03 ; |XX......| mirrored
PF2Room13:
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $01 ; |X.......| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $07 ; |XXX.....| mirrored
    .byte $07 ; |XXX.....| mirrored
    .byte $07 ; |XXX.....| mirrored
PF2Room14:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room15:
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
PF2Room16:
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $C0 ; |......XX| mirrored
    .byte $E0 ; |.....XXX| mirrored
    .byte $F0 ; |....XXXX| mirrored
    .byte $F0 ; |....XXXX| mirrored
    .byte $F0 ; |....XXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
    .byte $30 ; |....XX..| mirrored
PF2Room17:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $76 ; |.XX.XXX.| mirrored
    .byte $76 ; |.XX.XXX.| mirrored
    .byte $76 ; |.XX.XXX.| mirrored
    .byte $F0 ; |....XXXX| mirrored
    .byte $F4 ; |..X.XXXX| mirrored
    .byte $70 ; |....XXX.| mirrored
    .byte $F0 ; |....XXXX| mirrored
    .byte $E0 ; |.....XXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room18:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $38 ; |...XXX..| mirrored
    .byte $10 ; |....X...| mirrored
    .byte $10 ; |....X...| mirrored
    .byte $10 ; |....X...| mirrored
    .byte $38 ; |...XXX..| mirrored
    .byte $6E ; |.XXX.XX.| mirrored
    .byte $34 ; |..X.XX..| mirrored
    .byte $52 ; |.X..X.X.| mirrored
    .byte $28 ; |...X.X..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room19:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room20:
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $07 ; |XXX.....| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $01 ; |X.......| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room21:
    .byte $C0 ; |......XX| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $00 ; |........| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $00 ; |........| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room22:
    .byte $00 ; |........| mirrored
    .byte $B0 ; |....XX.X| mirrored
    .byte $B0 ; |....XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $B0 ; |....XX.X| mirrored
    .byte $B0 ; |....XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $00 ; |........| mirrored
    .byte $B0 ; |....XX.X| mirrored
    .byte $B0 ; |....XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $B0 ; |....XX.X| mirrored
    .byte $B0 ; |....XX.X| mirrored
    .byte $C0 ; |......XX| mirrored
PF2Room23:
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room24:
    .byte $80 ; |.......X| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $86 ; |.XX....X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $00 ; |........| mirrored
    .byte $86 ; |.XX....X| mirrored
    .byte $86 ; |.XX....X| mirrored
    .byte $00 ; |........| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $86 ; |.XX....X| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $80 ; |.......X| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $86 ; |.XX....X| mirrored
    .byte $80 ; |.......X| mirrored
PF2Room25:
    .byte $00 ; |........| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $B6 ; |.XX.XX.X| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
PF2Room26:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $03 ; |XX......| mirrored
    .byte $57 ; |XXX.X.X.| mirrored
    .byte $7F ; |XXXXXXX.| mirrored
    .byte $7F ; |XXXXXXX.| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
PF2Room27:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room28:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $1F ; |XXXXX...| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $3F ; |XXXXXX..| mirrored
    .byte $1F ; |XXXXX...| mirrored
    .byte $1F ; |XXXXX...| mirrored
    .byte $0F ; |XXXX....| mirrored
    .byte $06 ; |.XX.....| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room29:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $68 ; |...X.XX.| mirrored
    .byte $74 ; |..X.XXX.| mirrored
    .byte $7E ; |.XXXXXX.| mirrored
    .byte $EE ; |.XXX.XXX| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $93 ; |XX..X..X| mirrored
    .byte $C6 ; |.XX...XX| mirrored
    .byte $FC ; |..XXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room30:
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $FF ; |XXXXXXXX| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
PF2Room31:
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $36 ; |.XX.XX..| mirrored
    .byte $00 ; |........| mirrored

