PF1Room0:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room1:
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
PF1Room2:
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
PF1Room3:
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $F0 ; |XXXX....|
    .byte $F0 ; |XXXX....|
    .byte $F0 ; |XXXX....|
    .byte $F0 ; |XXXX....|
    .byte $F0 ; |XXXX....|
    .byte $FF ; |XXXXXXXX|
PF1Room4:
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $0C ; |....XX..|
    .byte $1E ; |...XXXX.|
    .byte $3F ; |..XXXXXX|
PF1Room5:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room6:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room7:
    .byte $3F ; |..XXXXXX|
    .byte $3E ; |..XXXXX.|
    .byte $3E ; |..XXXXX.|
    .byte $1C ; |...XXX..|
    .byte $18 ; |...XX...|
    .byte $10 ; |...X....|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room8:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $08 ; |....X...|
    .byte $18 ; |...XX...|
    .byte $38 ; |..XXX...|
    .byte $7C ; |.XXXXX..|
    .byte $7C ; |.XXXXX..|
    .byte $7C ; |.XXXXX..|
PF1Room9:
    .byte $3F ; |..XXXXXX|
    .byte $3E ; |..XXXXX.|
    .byte $3E ; |..XXXXX.|
    .byte $1C ; |...XXX..|
    .byte $18 ; |...XX...|
    .byte $10 ; |...X....|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $08 ; |....X...|
    .byte $18 ; |...XX...|
    .byte $38 ; |..XXX...|
    .byte $7C ; |.XXXXX..|
    .byte $7C ; |.XXXXX..|
    .byte $3C ; |..XXXX..|
PF1Room10:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $F8 ; |XXXXX...|
    .byte $FC ; |XXXXXX..|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
PF1Room11:
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FC ; |XXXXXX..|
    .byte $F8 ; |XXXXX...|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room12:
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FC ; |XXXXXX..|
    .byte $F8 ; |XXXXX...|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $F8 ; |XXXXX...|
    .byte $FC ; |XXXXXX..|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
    .byte $FE ; |XXXXXXX.|
PF1Room13:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room14:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $C3 ; |XX....XX|
    .byte $C3 ; |XX....XX|
    .byte $00 ; |........|
    .byte $D8 ; |XX.XX...|
    .byte $D8 ; |XX.XX...|
    .byte $00 ; |........|
PF1Room15:
    .byte $00 ; |........|
    .byte $D8 ; |XX.XX...|
    .byte $D8 ; |XX.XX...|
    .byte $00 ; |........|
    .byte $C3 ; |XX....XX|
    .byte $C3 ; |XX....XX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room16:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|
PF1Room17:
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room18:
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|
PF1Room19:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $F3 ; |XXXX..XX|
    .byte $F3 ; |XXXX..XX|
    .byte $F3 ; |XXXX..XX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
PF1Room20:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room21:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
PF1Room22:
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $0E ; |....XXX.|
    .byte $0E ; |....XXX.|
    .byte $0E ; |....XXX.|
    .byte $0E ; |....XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
PF1Room23:
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $0E ; |....XXX.|
    .byte $0E ; |....XXX.|
    .byte $0E ; |....XXX.|
    .byte $0E ; |....XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $CE ; |XX..XXX.|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
PF1Room24:
    .byte $80 ; |X.......|
    .byte $86 ; |X....XX.|
    .byte $86 ; |X....XX.|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $B8 ; |X.XXX...|
    .byte $B8 ; |X.XXX...|
    .byte $BF ; |X.XXXXXX|
    .byte $BF ; |X.XXXXXX|
    .byte $BF ; |X.XXXXXX|
    .byte $BF ; |X.XXXXXX|
PF1Room25:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $FF ; |XXXXXXXX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $FF ; |XXXXXXXX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room26:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $06 ; |.....XX.|
    .byte $06 ; |.....XX.|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $40 ; |.X......|
    .byte $EA ; |XXX.X.X.|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
    .byte $FF ; |XXXXXXXX|
PF1Room27:
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $8C ; |X...XX..|
    .byte $8C ; |X...XX..|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $0C ; |....XX..|
    .byte $8C ; |X...XX..|
    .byte $8C ; |X...XX..|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
    .byte $80 ; |X.......|
PF1Room28:
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $01 ; |.......X|
    .byte $03 ; |......XX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $03 ; |......XX|
    .byte $03 ; |......XX|
    .byte $01 ; |.......X|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
PF1Room29:
    .byte $E0 ; |XXX.....|
    .byte $E0 ; |XXX.....|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $07 ; |.....XXX|
    .byte $06 ; |.....XX.|
    .byte $06 ; |.....XX.|
    .byte $07 ; |.....XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E7 ; |XXX..XXX|
    .byte $E0 ; |XXX.....|
    .byte $E0 ; |XXX.....|
PF1Room30:
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C3 ; |XX....XX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $07 ; |.....XXX|
    .byte $C7 ; |XX...XXX|
    .byte $C7 ; |XX...XXX|
    .byte $C3 ; |XX....XX|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
    .byte $C0 ; |XX......|
PF1Room31:
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|
    .byte $DB ; |XX.XX.XX|
    .byte $DB ; |XX.XX.XX|
    .byte $00 ; |........|

